---
application:
  name: "tateti"
  project: "tateti"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 3000
routers:
- name: "main-tateti"
  routes:
  - application_name: "tateti"
    paths:
    - "/*"
